---
- name: include group vars
  include_vars: group_vars/mongo-rs.yml

- name: setup pip
  shell: "curl 'https://bootstrap.pypa.io/get-pip.py' -o 'get-pip.py'"
  become: true

- name: get pip
  shell: "python get-pip.py"
  become: true

- name: enable replication
  lineinfile:
    path: /etc/mongod.conf
    insertafter: "^#replication:"
    line: "  replSetName: my-mongo-set"
  become: true

- name: restart mongo
  systemd:
    name: mongod
    state: stopped
  become: true

- name: remove comment
  replace:
    path: /etc/mongod.conf
    regexp: "^#replication:"
    replace: "replication:"
  become: true

- name: Create /data/db
  file:
    path: /data/db
    owner: mongod
    group: mongod
    mode: '0755'
    recurse: yes
  become: yes

- name: kill existing mongodb process
  shell: "kill -9 $(pidof mongod)"
  ignore_errors: yes
  become: true

- name: Start mongo replica set 
  command: "mongod --fork --dbpath /data/db --replSet my-mongo-set --bind_ip 0.0.0.0 --logpath /var/log/mongod.log"
  async: 45
  poll: 0
  become: yes
