---
- name: setup pip
  shell: "curl 'https://bootstrap.pypa.io/get-pip.py' -o 'get-pip.py'"
  become: true

- name: get pip
  shell: "python get-pip.py"
  become: true

- name: enable replication
  lineinfile:
    path: /etc/mongod.conf
    insertafter: "^#replication:"
    line: "  replSetName: my-mongo-set"
  become: true

- name: remove comment
  replace:
    path: /etc/mongod.conf
    regexp: "^#replication:"
    replace: "replication:"
  become: true

- name: restart mongo
  systemd: 
    name: mongod
    state: restarted     
  become: true

- name: Copy replica set config
  copy:
    src: "{{ item }}"
    dest: /home/ec2-user/
  with_items:
    - mongo-replica-set.js
    - mongo-admin-user.js
    - add-slave-arbiter.js

- name: Ensure replica set exists
  shell: "mongo < /home/ec2-user/mongo-replica-set.js && sleep 15"

- name: Add slave & arbiter
  shell: "mongo < /home/ec2-user/add-slave-arbiter.js && sleep 20"

- name: Create Administrator user
  shell: "mongo < /home/ec2-user/mongo-admin-user.js"